services:
  ipfs-autoscan:
    build:
      context: .
      args:
        KUBO_IMAGE_TAG: latest
    image: ghcr.io/bstone108/ipfs-cid-docker:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      CONFIG_PATH: /config
      SCAN_PATHS: /mnt
      RESCAN_INTERVAL: 15m
      SCAN_PRIORITY: low
      UPLOAD_BANDWIDTH_LIMIT: 10mbit
      # IPFS_PATH: /config/ipfs
      # INDEX_DB_PATH: /config/index/index.db
      # INDEX_EXPORT_PATH: /config/index/current-index.json
      # IPFS_PROFILE: server
      # BANDWIDTH_INTERFACE: eth0
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./config:/config
      - /stuff/stupidity/whatever:/mnt/whatever:ro
